name: Sync to Hugging Face hub
on:
  push:
    branches: [main]


# name: Handle Release
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        run: actions/checkout@main
      - name: Generate the artifacts
        run: nikhil-xyz/github-action-build@main
      - name: Upload the artifacts
        run: nikhil-xyz/github-action-publish-binaries@main
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://nikhil5678:$HF_TOKEN@huggingface.co/spaces/nikhil5678/comment-toxicity-model main
