
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
     
      - name: github-action-publish-binaries
        uses: skx/github-action-publish-binaries@release-2.0
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://nikhil5678:$HF_TOKEN@huggingface.co/spaces/nikhil5678/comment-toxicity-model main
