name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: True
      - name: LFS Install
        run: git lfs install
      - name: LFS Track1
        run: git lfs track *.pkl
      - name: LFS Track2
        run: git lfs track *.h5
      - name: LFS Attributes
        run: git add .gitattributes
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://nikhil5678:$HF_TOKEN@huggingface.co/spaces/nikhil5678/comment-toxicity-model main
